# Form implementation generated from reading ui file 'Gui.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore,QtWidgets,QtGui
from PyQt6.QtCore import *
from PyQt6.QtWidgets import *
from PyQt6.QtGui import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 16777215))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.MainMenu = QtWidgets.QWidget()
        self.MainMenu.setObjectName("MainMenu")
        self.pushButton = QtWidgets.QPushButton(self.MainMenu)
        self.pushButton.setGeometry(QtCore.QRect(600, 10, 120, 20))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.MainMenu, "")
        self.Tables = QtWidgets.QWidget()
        self.Tables.setObjectName("Tables")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.Tables)
        self.verticalScrollBar.setGeometry(QtCore.QRect(770, 0, 20, 560))
        self.verticalScrollBar.setMinimumSize(QtCore.QSize(10, 0))
        self.verticalScrollBar.setMaximumSize(QtCore.QSize(1677721, 16777215))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.tabWidget.addTab(self.Tables, "")
        self.Graphics = QtWidgets.QWidget()
        self.Graphics.setObjectName("Graphics")
        self.tabWidget.addTab(self.Graphics, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calc1.0"))
        self.pushButton.setText(_translate("MainWindow", "Произвести расчёт"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MainMenu), _translate("MainWindow", "Main menu"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tables), _translate("MainWindow", "Tables"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Graphics), _translate("MainWindow", "Graphics"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
