aggregation_functions: [
    'Среднее значение времени реализации функций'
] # 'Сумма', 'Среднее значение', 'Среднеквадратичное отклонение', max, min, countd - возможные функции агрегации
rows:
    'Ликвидация последствий попытки доступа нарушителей к аппаратным и программным средствам КФЗ':
      formulae1: '0.15 * o_1'
    'Ликвидация последствий попытки анализа нарушителями состояния охраняемой зоны':
      formulae1: '0.3 * o_2'
    'Ликвидация последствий попытки блокирования нарушителями информации в КФЗ':
      formulae1: '0.1 * o_3'
    'Ликвидация последствий попытки проникновения нарушителей в охраняемую зону':
      formulae1: '0.35 * o_4'