aggregation_functions_captions: [
    'Среднее значение времени реализации функций'
] # 'Сумма', 'Среднее значение', 'Среднеквадратичное отклонение', max, min, countd - возможные функции агрегации
rows:
    'Ликвидация последствий попытки доступа нарушителей к аппаратным и программным средствам КФЗ':
      variable1: 'nu_1_avg'
      formulae1: '0.15 * o_3_1_avg'
    'Ликвидация последствий попытки анализа нарушителями состояния охраняемой зоны':
      variable1: 'nu_2_avg'
      formulae1: '0.3 * o_3_2_avg'
    'Ликвидация последствий попытки блокирования нарушителями информации в КФЗ':
      variable1: 'nu_3_avg'
      formulae1: '0.1 * o_3_3_avg'
    'Ликвидация последствий попытки проникновения нарушителей в охраняемую зону':
      variable1: 'nu_4_avg'
      formulae1: '0.35 * o_3_4_avg'