aggregation_functions: [
    'Среднее значение времени реализации функций'
] # 'Сумма', 'Среднее значение', 'Среднеквадратичное отклонение', max, min, countd - возможные функции агрегации
rows:
    'Своевременность реагирования на попытку доступа нарушителей к аппаратным и программным средствам КФЗ':
      formulae1: '(t_1_avg - nu_1_avg) / (4 * s_1) * (1 + erf(o_1 / (s_1 * sqrt(2)) + 0.25 * exp(o_1 ^ 2 / (2 * o_1 ^ 2)) - 0.125 * (1 + erf(o_1 ^ 2 / (2 * s_1 ^ 2)))'
    'Своевременность реагирования на попытку анализа нарушителями состояния охраняемой зоны':
      formulae1: '(t_2_avg - nu_2_avg) / (4 * s_2) * (1 + erf(o_2 / (s_2 * sqrt(2)) + 0.25 * exp(o_2 ^ 2 / (2 * o_2 ^ 2)) - 0.125 * (1 + erf(o_2 ^ 2 / (2 * s_2 ^ 2)))'
    'Своевременность реагирования на попытку блокирования нарушителями информации в КФЗ':
      formulae1: '(t_3_avg - nu_3_avg) / (4 * s_3) * (1 + erf(o_3 / (s_3 * sqrt(2)) + 0.25 * exp(o_3 ^ 2 / (2 * o_3 ^ 2)) - 0.125 * (1 + erf(o_3 ^ 2 / (2 * s_3 ^ 2)))'
    'Своевременность реагирования на попытку проникновения нарушителей в охраняемую зону':
      formulae1: '(t_4_avg - nu_4_avg) / (4 * s_4) * (1 + erf(o_4 / (s_4 * sqrt(2)) + 0.25 * exp(o_4 ^ 2 / (2 * o_4 ^ 2)) - 0.125 * (1 + erf(o_4 ^ 2 / (2 * s_4 ^ 2)))'