aggregation_functions: [
    'Среднее значение времени реализации функций'
] # 'Сумма', 'Среднее значение', 'Среднеквадратичное отклонение', max, min, countd - возможные функции агрегации
rows:
    'Своевременность реагирования на попытку доступа нарушителей к аппаратным и программным средствам КФЗ':
      variable1: 'e_1'
      formulae1: '(t_3_1_avg - nu_1_avg) / (4 * s_3_1) * (1 + erf(o_3_1_avg / (s_3_1 * sqrt(2)) + 0.25 * exp(o_3_1_avg ^ 2 / (2 * o_3_1_avg ^ 2)) - 0.125 * (1 + erf(o_3_1_avg ^ 2 / (2 * s_3_1 ^ 2)))'
    'Своевременность реагирования на попытку анализа нарушителями состояния охраняемой зоны':
      variable1: 'e_1'
      formulae1: '(t_3_2_avg - nu_2_avg) / (4 * s_3_2) * (1 + erf(o_3_2_avg / (s_3_2 * sqrt(2)) + 0.25 * exp(o_3_2_avg ^ 2 / (2 * o_3_2_avg ^ 2)) - 0.125 * (1 + erf(o_3_2_avg ^ 2 / (2 * s_3_2 ^ 2)))'
    'Своевременность реагирования на попытку блокирования нарушителями информации в КФЗ':
      variable1: 'e_1'
      formulae1: '(t_3_3_avg - nu_3_avg) / (4 * s_3_3) * (1 + erf(o_3_3_avg / (s_3_3 * sqrt(2)) + 0.25 * exp(o_3_3_avg ^ 2 / (2 * o_3_3_avg ^ 2)) - 0.125 * (1 + erf(o_3_3_avg ^ 2 / (2 * s_3_3 ^ 2)))'
    'Своевременность реагирования на попытку проникновения нарушителей в охраняемую зону':
      variable1: 'e_1'
      formulae1: '(t_3_4_avg - nu_4_avg) / (4 * s_3_4) * (1 + erf(o_3_4_avg / (s_3_4 * sqrt(2)) + 0.25 * exp(o_3_4_avg ^ 2 / (2 * o_3_4_avg ^ 2)) - 0.125 * (1 + erf(o_3_4_avg ^ 2 / (2 * s_3_4 ^ 2)))'
    'E':
      variable1: 'E'
      formulae1: '1 - (1 - e_1) * (1 - e_2) * (1 - e_3) * (1 - e_4)'