aggregation_functions_captions: [
    'Среднее значение времени реализации функций'
] # 'Сумма', 'Среднее значение', 'Среднеквадратичное отклонение', max, min, countd - возможные функции агрегации
rows:
    'Осуществление доступа к периферийным устройствам охранного мониторинга территории и акватории':
      variable1: 't_2_1_avg'
      formulae1: 't_1_1_avg + 0.5 * t_1_2_avg + 0.5 * t_1_3_avg'
    'Осуществление доступа к серверу поста управления':
      variable1: 't_2_2_avg'
      formulae1: '0.25 * t_1_4_avg + 0.25 * t_1_5_avg + 0.25 * t_1_6_avg + 0.25 * t_1_7_avg'
    'Анализ состояния подходов к охраняемой зоне':
      variable1: 't_2_3_avg'
      formulae1: 't_1_8_avg + t_1_9_avg '
    'Анализ состояния инженерной защиты охраняемой зоны':
      variable1: 't_2_4_avg'
      formulae1: 't_1_10_avg + t_1_11_avg + t_1_12_avg'
    'Анализ состояния систем охранного мониторинга территории и акватории охраняемой зоны':
      variable1: 't_2_5_avg'
      formulae1: 't_1_13_avg + t_1_14_avg + t_1_15_avg + t_1_16_avg + t_1_17_avg'
    'Блокирование информации устройств охранного мониторинга территории и акватории':
      variable1: 't_2_6_avg'
      formulae1: 't_1_18_avg + t_1_19_avg '
    'Блокирование работы оборудования управления КФЗ':
      variable1: 't_2_7_avg'
      formulae1: 't_1_20_avg + t_1_21_avg'
    'Блокирование информации АРМов ДЛ':
      variable1: 't_2_8_avg'
      formulae1: 't_1_22_avg + 0.5 * t_1_23_avg '
    'Преодоление периметра территории и акватории охраняемой зоны':
      variable1: 't_2_9_avg'
      formulae1: '0.2 * t_1_24_avg + 0.2 * t_1_25_avg + 0.2 * t_1_26_avg + 0.2 * t_1_27_avg + 0.2 * t_1_28_avg'
    'Продвижение нарушителей внутри территории и акватории охраняемой зоны к цели':
      variable1: 't_2_10_avg'
      formulae1: '0.33 * t_1_29_avg + 0.33 * (t_1_30_avg + t_1_31_avg + t_1_32_avg) + 0.33 * t_1_33_avg'
    'Выполнение задания и уход нарушителей с территории и акватории охраняемой зоны':
      variable1: 't_2_11_avg'
      formulae1: 't_1_34_avg + 0.33 * t_1_35_avg + 0.33 * (t_1_36_avg + t_1_37_avg + t_1_38_avg) + 0.33 * t_1_39_avg'