aggregation_functions: [
    'Среднее значение времени реализации функций',
    'Среднеквадратичное отклонение'
] # 'Сумма', 'Среднее значение', 'Среднеквадратичное отклонение', max, min, countd - возможные функции агрегации
rows:
    'Выявление факта доступа нарушителей к периферийным устройствам охранного мониторинга территории и акватории':
      formulae1: '0.33 * (o_1 + o_2 + o_3)'
      formulae2: 'sqrt(s_1 ^ 2 + s_2 ^ 2 + s_3^ 2)'
    'Выявление факта доступа нарушителей к серверу поста управления':
      formulae1: '0.25 * (o_4 + o_5 + o_6 + o_7)'
      formulae2: 'sqrt(s_4 ^ 2 + s_5 ^ 2 + s_6 ^ 2 + s_7 ^ 2)'
    'Выявление факта анализа нарушителями состояния подходов к охраняемой зоне ':
      formulae1: '0.5 * (o_8 + o_9)'
      formulae2: 'sqrt(s_8 ^ 2 + s_9 ^ 2)'
    'Выявление факта анализа нарушителями состояния инженерной защиты охраняемой зоны':
      formulae1: '0.33 * (o_10 + o_11 + 0_12)'
      formulae2: 'sqrt(s_10 ^ 2 + s_11 ^ 2 + s_12 ^ 2)'
    'Выявление факта анализа нарушителями состояния систем охранного мониторинга территории и акватории охраняемой зоны':
      formulae1: '0.25 * (o_13 + o_14 + 0_15 + o_16 + o_17)'
      formulae2: 'sqrt(s_13 ^ 2 + s_14 ^ 2 + s_15 ^ 2 + s_16 ^ 2 + s_17 ^ 2)'
    'Выявление факта блокирования нарушителями информации устройств охранного мониторинга территории и акватории ':
      formulae1: '0.5 * (o_18 + o_19)'
      formulae2: 'sqrt(s_18 ^ 2 + s_19 ^ 2)'
    'Выявление факта блокирования нарушителями работы оборудования управления КФЗ':
      formulae1: '0.5 * (o_20 + o_21)'
      formulae2: 'sqrt(s_20 ^ 2 + s_21 ^ 2)'
    'Выявление факта блокирования нарушителями информации АРМ-ов ДЛ':
      formulae1: '0.5 * (o_22 + o_23)'
      formulae2: 'sqrt(s_22 ^ 2 + s_23 ^ 2)'
    'Выявление факта преодоления нарушителями периметра территории и акватории охраняемой зоны':
      formulae1: '0.2 * (o_24 + o_25 + o_26 + o_27 + o_28)'
      formulae2: 'sqrt(s_24 ^ 2 + s_25 ^ 2 + s_26 ^ 2 + s_27 ^ 2 + s_28 ^ 2)'
    'Выявление факта продвижения нарушителей внутри территории и акватории охраняемой зоны к цели':
      formulae1: '0.2 * (o_29 + o_30 + o_31 + o_32 + o_33)'
      formulae2: 'sqrt(s_29 ^ 2 + s_30 ^ 2 + s_31 ^ 2 + s_32 ^ 2 + s_33 ^ 2)'
    'Выявление факта выполнения нарушителями задания и ухода с территории и акватории охраняемой зоны':
      formulae1: '0.16 * (o_34 + o_35 + o_36 + o_37 + o_38 + o_39)'
      formulae2: 'sqrt(s_34 ^ 2 + s_35 ^ 2 + s_36 ^ 2 + s_37 ^ 2 + s_38 ^ 2 + s_39 ^ 2)'






