aggregation_functions: [
    'Среднее значение времени реализации функций',
    'Среднеквадратичное отклонение'
] # 'Сумма', 'Среднее значение', 'Среднеквадратичное отклонение', max, min, countd - возможные функции агрегации
rows:
    'Выявление факта доступа нарушителей к периферийным устройствам охранного мониторинга территории и акватории':
      formulae1: '0.33 * (o_1 + o_2 + o_3)'
      formulae2: 'sqrt(s_1 + s_2 + s_3)'
    'Выявление факта доступа нарушителей к серверу поста управления':
      formulae1: '0.25 * (o_4 + o_5 + o_6 + o_7)'
      formulae2: 'sqrt(s_4 + s_5 + s_6 + s_7)'
    'Выявление факта анализа нарушителями состояния подходов к охраняемой зоне ':
      formulae1: '0.5 * (o_8 + o_9)'
      formulae2: 'sqrt(s_8 + s_9 )'
    'Выявление факта анализа нарушителями состояния инженерной защиты охраняемой зоны':
      formulae1: '0.33 * (o_10 + o_11 + 0_12)'
      formulae2: 'sqrt(s_10 + s_11 + s_12 )'
    'Выявление факта анализа нарушителями состояния систем охранного мониторинга территории и акватории охраняемой зоны':
      formulae1: '0.25 * (o_13 + o_14 + 0_15 + o_16 + o_17)'
      formulae2: 'sqrt(s_13 + s_14 + s_15 + s_16 + s_17)'
    'Выявление факта блокирования нарушителями информации устройств охранного мониторинга территории и акватории ':
      formulae1: '0.5 * (o_18 + o_19)'
      formulae2: 'sqrt(s_18 + s_19)'
    'Выявление факта блокирования нарушителями работы оборудования управления КФЗ':
      formulae1: '0.5 * (o_20 + o_21)'
      formulae2: 'sqrt(s_20 + s_21)'
    'Выявление факта блокирования нарушителями информации АРМ-ов ДЛ':
      formulae1: '0.5 * (o_22 + o_23)'
      formulae2: 'sqrt(s_22 + s_23)'
    'Выявление факта преодоления нарушителями периметра территории и акватории охраняемой зоны':
      formulae1: '0.2 * (o_24 + o_25 + o_26 + o_27 + o_28)'
      formulae2: 'sqrt(s_24 + s_25 + s_26 + s_27 + s_28)'
    'Выявление факта продвижения нарушителей внутри территории и акватории охраняемой зоны к цели':
      formulae1: '0.2 * (o_29 + o_30 + o_31 + o_32 + o_33)'
      formulae2: 'sqrt(s_27 + s_30 + s_31 + s_32 + s_33)'
    'Выявление факта выполнения нарушителями задания и ухода с территории и акватории охраняемой зоны':
      formulae1: '0.16 * (o_34 + o_35 + o_36 + o_37 + o_38 + o_39)'
      formulae2: 'sqrt(s_34 + s_35 + s_36 + s_37 + s_38 + s_39)'






