aggregation_functions: [
    'Среднее значение времени реализации функций',
    'Среднеквадратичное отклонение'
] # 'Сумма', 'Среднее значение', 'Среднеквадратичное отклонение', max, min, countd - возможные функции агрегации
rows:
    'Установление факта реализации нарушителями этапа доступа к аппаратным и программным средствам КФЗ':
      formulae1: '0.5 * (o_1 + o_2)'
      formulae2: 'sqrt(s_1 + s_2)'
    'Установление факта реализации нарушителями этапа анализа состояния охраняемой зоны':
      formulae1: '0.33 * (o_3 + o_4 + o_5)'
      formulae2: 'sqrt(s_3 + s_4 + s_5)'
    'Установление факта реализации нарушителями этапа блокирования информации в КФЗ':
      formulae1: '0.33 * (o_6 + o_7 + o_8)'
      formulae2: 'sqrt(s_6 + s_7 + s_8)'
    'Выявление факта анализа нарушителями состояния инженерной защиты охраняемой зоны':
      formulae1: '0.33 * (o_9 + o_10 + o_11)'
      formulae2: 'sqrt(s_9 + s_10 + s_11)'