aggregation_functions: [
    'Среднее значение времени реализации функций'
] # 'Сумма', 'Среднее значение', 'Среднеквадратичное отклонение', max, min, countd - возможные функции агрегации
rows:
    'Осуществление доступа к периферийным устройствам охранного мониторинга территории и акватории':
      formulae: 't_1_avg + 0.5 * t_2_avg + 0.5 * t_3_avg'
    'Осуществление доступа к серверу поста управления':
      formulae: '0.25 * t_4_avg + 0.25 * t_5_avg + 0.25 * t_6_avg + 0.25 * t_7_avg'
    'Анализ состояния подходов к охраняемой зоне':
      formulae: 'x * t_i_avg + '
    'Анализ состояния инженерной защиты охраняемой зоны':
      formulae: 'x * t_i_avg + '
    'Анализ состояния систем охранного мониторинга территории и акватории охраняемой зоны':
      formulae: 'x * t_i_avg + '
    'Блокирование информации устройств охранного мониторинга территории и акватории':
      formulae: 'x * t_i_avg + '
    'Блокирование работы оборудования управления КФЗ':
      formulae: 'x * t_i_avg + '
    'Блокирование информации АРМов ДЛ':
      formulae: 'x * t_i_avg + '
    'Преодоление периметра территории и акватории охраняемой зоны':
      formulae: 'x * t_i_avg + '
    'Продвижение нарушителей внутри территории и акватории охраняемой зоны к цели':
      formulae: 'x * t_i_avg + '
    'Выполнение задания и уход нарушителей с территории и акватории охраняемой зоны':
      formulae: 'x * t_i_avg + '