expert_assessments_caption: 'Данные экспертов относительно времени реализации функций'
expert_assessments_num: 10
aggregation_functions: [
    'Среднее значение'
] # 'Сумма', 'Среднее значение', 'Среднеквадратичное отклонение', max, min, countd - возможные функции агрегации
rows: [
    'Уяснение особенностей процедур кодирования',
    'Уяснение особенностей процедур приема/передачи мониторинговой информации',
    'Уяснение особенностей процедур приема/передачи информации телеуправления',
    'Осуществление доступа к каналам обмена информацией',
    'Осуществление доступа к резервным каналам',
    'Осуществление доступа к информации АРМ дежурного оператора',
    'Осуществление доступа к информации АРМ дежурного смены',
    'Анализ конфигурации периметра территории охраняемой зоны',
    'Анализ вариантов проникновения через акваторию в охраняемую зону',
    'Оценка состояния ограждения территории охраняемой зоны',
    'Оценка возможности проникновения через оборудование въезда/выезда в охраняемую зону',
    'Оценка возможности проникновения через боновые заграждения акватории охраняемой зоны',
    'Анализ состояния системы периметральной сигнализации',
    'Анализ состояния системы гидроакустической защиты',
    'Анализ состояния системы распределенного видеонаблюдения',
    'Анализ состояния системы радиолокационного наблюдения',
    'Анализ маршрутов наряда',
    'Блокирование информации средств мониторинга',
    'Блокирование информации телеуправления охранным мониторинговым оборудованием',
    'Блокирование информации каналов обмена данными',
    'Блокирование информации резервных каналов',
    'Блокирование информации АРМ дежурного оператора',
    'Блокирование информации АРМ дежурного смены',
    'Проникновение в охраняемую зону через оборудование въезда/выезда',
    'Проникновение через боновые заграждения акватории охраняемой зоны',
    'Проникновение путем подкопа под внешним ограждением',
    'Проникновение путем перелаза через внешнее ограждение',
    'Проникновение путем разрушения внешнего ограждения',
    'Проникновение в охраняемую зону по подложным идентификационным признакам, либо через дежурного поста',
    'Проникновение на территорию и акваторию через зону действия радиолокационных средств',
    'Проникновение на территорию и акваторию через зону обнаружения системы видеонаблюдения',
    'Проникновение на территорию в обход средств периметральной сигнализации',
    'Проникновение в акваторию охраняемой зоны в обход системы гидроакустической защиты',
    'Выполнение нарушителями задания',
    'Уход из охраняемой зоны по подложным идентификационным признакам, либо через дежурного поста',
    'Уход с территории и акватории через зону действия радиолокационных средств',
    'Уход с территории и акватории через зону обнаружения системы видеонаблюдения',
    'Уход с территории в обход средств периметральной сигнализации',
    'Уход с акватории охраняемой зоны в обход системы гидроакустической защиты'
]