expert_assessments_caption: 'Данные экспертов относительно времени реализации функций'
expert_assessments_num: 10
aggregation_functions_captions: [
    'Среднее значение'
]
rows:
    'Обнаружение попытки уяснения нарушителями особенностей реализации процедур кодирования':
      variable1: 'o_1_1_avg'
      formulae1: 'avg' # sum, avg, max, min, countd - возможные функции агрегации
      variable2: 's_1_1_avg'
      formulae2: 'msd'
    'Обнаружение попытки уяснения нарушителями особенностей реализации процедур приема/передачи мониторинговой информации':
      variable1: 'o_1_2_avg'
      formulae1: 'avg'
      variable2: 's_1_2_avg'
      formulae2: 'msd'
    'Обнаружение попытки уяснения нарушителями особенностей реализации процедур приема/передачи информации телеуправления':
      variable1: 'o_1_3_avg'
      formulae1: 'avg'
      variable2: 's_1_3'
      formulae2: 'msd'
    'Обнаружение попытки доступа нарушителей к каналам обмена информацией':
      variable1: 'o_1_4_avg'
      formulae1: 'avg'
      variable2: 's_1_4'
      formulae2: 'msd'
    'Обнаружение попытки доступа нарушителей к резервным каналам':
      variable1: 'o_1_5_avg'
      formulae1: 'avg'
      variable2: 's_1_5'
      formulae2: 'msd'
    'Обнаружение попытки доступа нарушителей к информации АРМ дежурного оператора':
      variable1: 'o_1_6_avg'
      formulae1: 'avg'
      variable2: 's_1_6'
      formulae2: 'msd'
    'Обнаружение попытки доступа нарушителей к информации АРМ дежурного смены':
      variable1: 'o_1_7_avg'
      formulae1: 'avg'
      variable2: 's_1_7'
      formulae2: 'msd'
    'Обнаружение попытки анализа нарушителями конфигурации периметра территории охраняемой зоны':
      variable1: 'o_1_8_avg'
      formulae1: 'avg'
      variable2: 's_1_8'
      formulae2: 'msd'
    'Обнаружение попытки анализа нарушителями вариантов проникновения через акваторию в охраняемую зону':
      variable1: 'o_1_9_avg'
      formulae1: 'avg'
      variable2: 's_1_9'
      formulae2: 'msd'
    'Обнаружение попытки оценки нарушителями состояния ограждения территории охраняемой зоны':
      variable1: 'o_1_10_avg'
      formulae1: 'avg'
      variable2: 's_1_10'
      formulae2: 'msd'
    'Обнаружение попытки оценки нарушителями возможности проникновения через оборудование въезда/выезда в охраняемую зону':
      variable1: 'o_1_11_avg'
      formulae1: 'avg'
      variable2: 's_1_11'
      formulae2: 'msd'
    'Обнаружение попытки оценки нарушителями возможности проникновения через боновые заграждения акватории охраняемой зоны':
      variable1: 'o_1_12_avg'
      formulae1: 'avg'
      variable2: 's_1_12'
      formulae2: 'msd'
    'Обнаружение попытки анализа нарушителями состояния системы периметральной сигнализации':
      variable1: 'o_1_13_avg'
      formulae1: 'avg'
      variable2: 's_1_13'
      formulae2: 'msd'
    'Обнаружение попытки анализа нарушителями состояния системы гидроакустической защиты':
      variable1: 'o_1_14_avg'
      formulae1: 'avg'
      variable2: 's_1_14'
      formulae2: 'msd'
    'Обнаружение попытки анализа нарушителями состояния системы распределенного видеонаблюдения':
      variable1: 'o_1_15_avg'
      formulae1: 'avg'
      variable2: 's_1_15'
      formulae2: 'msd'
    'Обнаружение попытки анализа нарушителями состояния системы радиолокационного наблюдения':
      variable1: 'o_1_16_avg'
      formulae1: 'avg'
      variable2: 's_1_16'
      formulae2: 'msd'
    'Обнаружение попытки анализа нарушителями маршрутов наряда':
      variable1: 'o_1_17_avg'
      formulae1: 'avg'
      variable2: 's_1_17'
      formulae2: 'msd'
    'Обнаружение попытки блокирования нарушителями информации средств мониторинга':
      variable1: 'o_1_18_avg'
      formulae1: 'avg'
      variable2: 's_1_18'
      formulae2: 'msd'
    'Обнаружение попытки блокирования нарушителями информации телеуправления охранным мониторинговым оборудованием':
      variable1: 'o_1_19_avg'
      formulae1: 'avg'
      variable2: 's_1_19'
      formulae2: 'msd'
    'Обнаружение попытки блокирования нарушителями информации каналов обмена данными':
      variable1: 'o_1_20_avg'
      formulae1: 'avg'
      variable2: 's_1_20'
      formulae2: 'msd'
    'Обнаружение попытки блокирования нарушителями информации резервных каналов':
      variable1: 'o_1_21_avg'
      formulae1: 'avg'
      variable2: 's_1_21'
      formulae2: 'msd'
    'Обнаружение попытки блокирования нарушителями информации АРМ дежурного оператора':
      variable1: 'o_1_22_avg'
      formulae1: 'avg'
      variable2: 's_1_22'
      formulae2: 'msd'
    'Обнаружение попытки блокирования нарушителями информации АРМ дежурного смены':
      variable1: 'o_1_23_avg'
      formulae1: 'avg'
      variable2: 's_1_23'
      formulae2: 'msd'
    'Обнаружение попытки проникновения в охраняемую зону через оборудование въезда/выезда':
      variable1: 'o_1_24_avg'
      formulae1: 'avg'
      variable2: 's_1_24'
      formulae2: 'msd'
    'Обнаружение попытки проникновения охраняемую зону через боновые заграждения акватории охраняемой зоны':
      variable1: 'o_1_25_avg'
      formulae1: 'avg'
      variable2: 's_1_25'
      formulae2: 'msd'
    'Обнаружение попытки проникновения в охраняемую зону путем подкопа под внешним ограждением':
      variable1: 'o_1_26_avg'
      formulae1: 'avg'
      variable2: 's_1_26'
      formulae2: 'msd'
    'Обнаружение попытки проникновения в охраняемую зону путем перелаза через внешнее ограждение':
      variable1: 'o_1_27_avg'
      formulae1: 'avg'
      variable2: 's_1_27'
      formulae2: 'msd'
    'Обнаружение попытки проникновения в охраняемую зону путем разрушения внешнего ограждения':
      variable1: 'o_1_28_avg'
      formulae1: 'avg'
      variable2: 's_1_28'
      formulae2: 'msd'
    'Обнаружение попытки проникновения в охраняемую зону по подложным идентификационным признакам, либо через дежурного поста':
      variable1: 'o_1_29_avg'
      formulae1: 'avg'
      variable2: 's_1_29'
      formulae2: 'msd'
    'Обнаружение попытки проникновения на территорию и акваторию через зону действия радиолокационных средств':
      variable1: 'o_1_30_avg'
      formulae1: 'avg'
      variable2: 's_1_30'
      formulae2: 'msd'
    'Обнаружение попытки проникновения на территорию и акваторию через зону обнаружения системы видеонаблюдения':
      variable1: 'o_1_31_avg'
      formulae1: 'avg'
      variable2: 's_1_31'
      formulae2: 'msd'
    'Обнаружение попытки проникновения на территорию в обход средств периметральной сигнализации':
      variable1: 'o_1_32_avg'
      formulae1: 'avg'
      variable2: 's_1_32'
      formulae2: 'msd'
    'Обнаружение попытки проникновения в акваторию охраняемой зоны в обход системы гидроакустической защиты':
      variable1: 'o_1_33_avg'
      formulae1: 'avg'
      variable2: 's_1_33'
      formulae2: 'msd'
    'Обнаружение попытки выполнения нарушителями задания':
      variable1: 'o_1_34_avg'
      formulae1: 'avg'
      variable2: 's_1_34'
      formulae2: 'msd'
    'Обнаружение попытки ухода из охраняемой зоны по подложным идентификационным признакам, либо через дежурного поста':
      variable1: 'o_1_35_avg'
      formulae1: 'avg'
      variable2: 's_1_35'
      formulae2: 'msd'
    'Обнаружение попытки ухода с территории и акватории через зону действия радиолокационных средств':
      variable1: 'o_1_36_avg'
      formulae1: 'avg'
      variable2: 's_1_36'
      formulae2: 'msd'
    'Обнаружение попытки ухода с территории и акватории через зону обнаружения системы видеонаблюдения':
      variable1: 'o_1_37_avg'
      formulae1: 'avg'
      variable2: 's_1_37'
      formulae2: 'msd'
    'Обнаружение попытки ухода с территории в обход средств периметральной сигнализации':
      variable1: 'o_1_38_avg'
      formulae1: 'avg'
      variable2: 's_1_38'
      formulae2: 'msd'
    'Обнаружение попытки ухода с акватории охраняемой зоны в обход системы гидроакустической защиты':
      variable1: 'o_1_38_avg'
      formulae1: 'avg'
      variable2: 's_1_38'
      formulae2: 'msd'