aggregation_functions_captions: [
    'Среднее значение времени реализации функций',
    'Среднеквадратичное отклонение'
] # 'Сумма', 'Среднее значение', 'Среднеквадратичное отклонение', max, min, countd - возможные функции агрегации
rows:
    'Выявление факта доступа нарушителей к периферийным устройствам охранного мониторинга территории и акватории':
      variable1: 'o_2_1_avg'
      formulae1: '0.33 * (o_1_1_avg + o_1_2_avg + o_1_3_avg)'
      variable2: 's_2_1'
      formulae2: 'sqrt(s_1_1 ^ 2 + s_1_2 ^ 2 + s_1_3 ^ 2)'
    'Выявление факта доступа нарушителей к серверу поста управления':
      variable1: 'o_2_2_avg'
      formulae1: '0.25 * (o_1_4_avg + o_1_5_avg + o_1_6_avg + o_1_7_avg)'
      variable2: 's_2_2'
      formulae2: 'sqrt(s_1_4 ^ 2 + s_1_5 ^ 2 + s_1_6 ^ 2 + s_1_7 ^ 2)'
    'Выявление факта анализа нарушителями состояния подходов к охраняемой зоне ':
      variable1: 'o_2_3_avg'
      formulae1: '0.5 * (o_1_8_avg + o_1_9_avg)'
      variable2: 's_2_3'
      formulae2: 'sqrt(s_1_8 ^ 2 + s_1_9 ^ 2)'
    'Выявление факта анализа нарушителями состояния инженерной защиты охраняемой зоны':
      variable1: 'o_2_4_avg'
      formulae1: '0.33 * (o_1_10_avg + o_1_11_avg + o_1_12_avg)'
      variable2: 's_2_4'
      formulae2: 'sqrt(s_1_10 ^ 2 + s_1_11 ^ 2 + s_1_12 ^ 2)'
    'Выявление факта анализа нарушителями состояния систем охранного мониторинга территории и акватории охраняемой зоны':
      variable1: 'o_2_5_avg'
      formulae1: '0.25 * (o_1_13_avg + o_1_14_avg + o_1_15_avg + o_1_16_avg + o_1_17_avg)'
      variable2: 's_2_5'
      formulae2: 'sqrt(s_1_13 ^ 2 + s_1_14 ^ 2 + s_1_15 ^ 2 + s_1_16 ^ 2 + s_1_17 ^ 2)'
    'Выявление факта блокирования нарушителями информации устройств охранного мониторинга территории и акватории ':
      variable1: 'o_2_6_avg'
      formulae1: '0.5 * (o_1_18_avg + o_1_19_avg)'
      variable2: 's_2_6'
      formulae2: 'sqrt(s_1_18 ^ 2 + s_1_19 ^ 2)'
    'Выявление факта блокирования нарушителями работы оборудования управления КФЗ':
      variable1: 'o_2_7_avg'
      formulae1: '0.5 * (o_1_20_avg + o_1_21_avg)'
      variable2: 's_2_7'
      formulae2: 'sqrt(s_1_20 ^ 2 + s_1_21 ^ 2)'
    'Выявление факта блокирования нарушителями информации АРМ-ов ДЛ':
      variable1: 'o_2_8_avg'
      formulae1: '0.5 * (o_1_22_avg + o_1_23_avg)'
      variable2: 's_2_8'
      formulae2: 'sqrt(s_1_22 ^ 2 + s_1_23 ^ 2)'
    'Выявление факта преодоления нарушителями периметра территории и акватории охраняемой зоны':
      variable1: 'o_2_9_avg'
      formulae1: '0.2 * (o_1_24_avg + o_1_25_avg + o_1_26_avg + o_1_27_avg + o_1_28_avg)'
      variable2: 's_2_9'
      formulae2: 'sqrt(s_1_24 ^ 2 + s_1_25 ^ 2 + s_1_26 ^ 2 + s_1_27 ^ 2 + s_1_28 ^ 2)'
    'Выявление факта продвижения нарушителей внутри территории и акватории охраняемой зоны к цели':
      variable1: 'o_2_10_avg'
      formulae1: '0.2 * (o_1_29_avg + o_1_30_avg + o_1_31_avg + o_1_32_avg + o_1_33_avg)'
      variable2: 's_2_10'
      formulae2: 'sqrt(s_1_29 ^ 2 + s_1_30 ^ 2 + s_1_31 ^ 2 + s_1_32 ^ 2 + s_1_33 ^ 2)'
    'Выявление факта выполнения нарушителями задания и ухода с территории и акватории охраняемой зоны':
      variable1: 'o_2_11_avg'
      formulae1: '0.16 * (o_1_34_avg + o_1_35_avg + o_1_36_avg + o_1_37_avg + o_1_38_avg + o_1_39_avg)'
      variable2: 's_2_11'
      formulae2: 'sqrt(s_1_34 ^ 2 + s_1_35 ^ 2 + s_1_36 ^ 2 + s_1_37 ^ 2 + s_1_38 ^ 2 + s_1_39 ^ 2)'






