aggregation_functions: [
    'Среднее значение времени реализации функций'
] # 'Сумма', 'Среднее значение', 'Среднеквадратичное отклонение', max, min, countd - возможные функции агрегации
rows:
    'Осуществление доступа к периферийным устройствам охранного мониторинга территории и акватории':
      formulae: 't_1_avg + 0.5 * t_2_avg + 0.5 * t_3_avg'
    'Осуществление доступа к серверу поста управления':
      formulae: '0.25 * t_4_avg + 0.25 * t_5_avg + 0.25 * t_6_avg + 0.25 * t_7_avg'
    'Анализ состояния подходов к охраняемой зоне':
      formulae: 't_8_avg + t_9_avg '
    'Анализ состояния инженерной защиты охраняемой зоны':
      formulae: 't_10_avg + t_11_avg + t_12_avg'
    'Анализ состояния систем охранного мониторинга территории и акватории охраняемой зоны':
      formulae: 't_13_avg + t_14_avg + t_15_avg + t_16_avg + t_17_avg  '
    'Блокирование информации устройств охранного мониторинга территории и акватории':
      formulae: 't_18_avg + t_19_avg '
    'Блокирование работы оборудования управления КФЗ':
      formulae: 't_20_avg + t_21_avg'
    'Блокирование информации АРМов ДЛ':
      formulae: 't_22_avg + 0.5 * t_23_avg '
    'Преодоление периметра территории и акватории охраняемой зоны':
      formulae: '0.2 * t_24_avg + 0.2 * t_25_avg + 0.2 * t_26_avg + 0.2 * t_27_avg + 0.2 * t_28_avg'
    'Продвижение нарушителей внутри территории и акватории охраняемой зоны к цели':
      formulae: '0.33 * t_29_avg + 0.33 * (t_30_avg + t_31_avg + t_32_avg) + 0.33 * t_33_avg'
    'Выполнение задания и уход нарушителей с территории и акватории охраняемой зоны':
      formulae: 't_34_avg + 0.33 * t_35_avg + 0.33 * (t_36_avg + t_37_avg + t_38_avg) + 0.33 * t_39_avg '