aggregation_functions_captions: [
    'Среднее значение времени реализации функций'
] # 'Сумма', 'Среднее значение', 'Среднеквадратичное отклонение', max, min, countd - возможные функции агрегации
rows:
    'Осуществление доступа к аппаратным и программным средствам КФЗ':
      formulae1: 't_1_avg + t_2_avg'
    'Анализ состояния охраняемой зоны':
      formulae1: 't_3_avg + t_4_avg + t_5_avg '
    'Блокирование информации в КФЗ':
      formulae1: '0.33 * t_6_avg + 0.33 * t_7_avg + 0.33 * t_8_avg'
    'Проникновение в охраняемую зону':
      formulae1: 't_9_avg + t_10_avg + t_11_avg'
