aggregation_functions: [
    'Среднее значение времени реализации функций'
] # 'Сумма', 'Среднее значение', 'Среднеквадратичное отклонение', max, min, countd - возможные функции агрегации
rows: [
    'Выявление факта доступа нарушителей к периферийным устройствам охранного мониторинга территории и акватории',
    'Выявление факта доступа нарушителей к серверу поста управления',
    'Выявление факта анализа нарушителями состояния подходов к охраняемой зоне',
    'Выявление факта анализа нарушителями состояния инженерной защиты охраняемой зоны',
    'Выявление факта анализа нарушителями состояния систем охранного мониторинга территории и акватории охраняемой зоны',
    'Выявление факта блокирования нарушителями информации устройств охранного мониторинга территории и акватории',
    'Выявление факта блокирования нарушителями работы оборудования управления КФЗ',
    'Выявление факта блокирования нарушителями информации АРМ-ов ДЛ',
    'Выявление факта преодоления нарушителями периметра территории и акватории охраняемой зоны',
    'Выявление факта продвижения нарушителей внутри территории и акватории охраняемой зоны к цели',
    'Выявление факта выполнения нарушителями задания и ухода с территории и акватории охраняемой зоны',

]