aggregation_functions_captions: [
    'Среднее значение времени реализации функций',
    'Среднеквадратичное отклонение'
] # 'Сумма', 'Среднее значение', 'Среднеквадратичное отклонение', max, min, countd - возможные функции агрегации
rows:
    'Установление факта реализации нарушителями этапа доступа к аппаратным и программным средствам КФЗ':
      variable1: 'o_3_1_avg'
      formulae1: '0.5 * (o_2_1_avg + o_2_2_avg)'
      variable2: 's_3_1'
      formulae2: 'sqrt(s_2_1 ^ 2 + s_2_2 ^ 2)'
    'Установление факта реализации нарушителями этапа анализа состояния охраняемой зоны':
      variable1: 'o_3_2_avg'
      formulae1: '0.33 * (o_2_3_avg + o_2_4_avg + o_2_5_avg)'
      variable2: 's_3_2'
      formulae2: 'sqrt(s_2_3 ^ 2 + s_2_4 ^ 2 + s_2_5 ^ 2)'
    'Установление факта реализации нарушителями этапа блокирования информации в КФЗ':
      variable1: 'o_3_3_avg'
      formulae1: '0.33 * (o_2_6_avg + o_2_7_avg + o_2_8_avg)'
      variable2: 's_3_3'
      formulae2: 'sqrt(s_2_6 ^ 2 + s_2_7 ^ 2 + s_2_8 ^ 2)'
    'Выявление факта анализа нарушителями состояния инженерной защиты охраняемой зоны':
      variable1: 'o_3_4_avg'
      formulae1: '0.33 * (o_2_9_avg + o_2_10_avg + o_2_11_avg)'
      variable2: 's_3_4'
      formulae2: 'sqrt(s_2_9 ^ 2 + s_2_10 ^ 2 + s_2_11 ^ 2)'